### ISSUE TITLE
Implement the C Value Library

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#149]
This library provides utility types for the C-FFI for C value types.

- [x] `Foreign.C.Value`: This module contains the types.
- [x] Contains utilities for marshalling between the C types and Luna inbuilt types.
- [x] Type definitions for C's types are consistent with the C ABI on x64 platform. (done by libffi/C* types)
- [x] Types are automatically unboxed when passed to a foreign call. (done by libffi)
- [x] Each type provides a `T.byteSize` function. 
- [x] `read`/`write` methods for reading/writing pointers
- [x] real implementation of prim* functions

**Comment by mikusp** [comment]
b665bb6b250ad40fb430fb1ec827cfb83f0784c1

**Comment by iamrecursion** [comment]
Looks great so far! Only thing would be to change the module name (this new one reflects the organisation better), and to name the classes as just (e.g.) `Int64`. That way you can do
```
import Foreign.C.Value as C
...
C.Int64...
```
Which is a lot more readable to me!

Is there a reason the `Ptr` type is in this library rather than the to be implemented `Foreign.C.Ptr`?

**Comment by mikusp** [comment]
Until we have "as" keyword in imports, Int would clash with the one defined
in Std.Base.

I can move Ptr anywhere, however I don't see any pros of having it in
another module.

1 mar 2018 16:19 "Ara Adkins" <notifications@github.com> napisał(a):

Assigned #149 <https://github.com/luna/luna/issues/149> to @mikusp
<https://github.com/mikusp>.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/luna/luna/issues/149#event-1499232478>, or mute the
thread

**Comment by iamrecursion** [comment]
Okay. We'll refactor names once we have the `as` imports! Do we want to combine this and `Foreign.C.Ptr` then? 

https://github.com/luna/luna/issues/150

**Comment by mikusp** [comment]
I guess it depends what functionality we need down the road. I'm getting by
having pretty much only "+" method. And having type safe pointers is a must
for the future, so maybe then they can get their own module?

1 mar 2018 16:42 "Ara Adkins" <notifications@github.com> napisał(a):

**Comment by iamrecursion** [comment]
That would make sense. I'd generally want `-` as well, but I can imagine that's likely to be enough to start with.

**Comment by iamrecursion** [comment]
Completed in #181.
