### ISSUE TITLE
Dataframes implementation

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna#206]
```
class Field Type:
    Field Real
    Field Int
    Field Text
    Field Category (List Text)

FieldValue:
    Value Real
    Value Int
    Value Text

class Column:
    name:: Maybe Text
    type :: Field Type
    data :: ManagedPointer None

class Dataframe:
    columns :: [Column]
```
define:
`selectColumns :: [Int] -> Dataframe`
`selectColumnsByName :: [Text] -> Dataframe`
`selectRows :: [Int] -> Dataframe`
`at :: Int -> Int -> FieldValue`
`mapColumn :: Int -> (FieldValue -> FieldValue) -> Dataframe`
`fill NA`

**Comment by piotrMocz** [comment]
I think it would be perfect to have these additional methods:
* `remove_na` (removing rows containing NA values)
* `to_csv`
* `from_csv`
* `selectColumnRange :: Int -> Int -> DataFrame` (trivial once `selectColumns` is implemented)
* `selectRowRange :: Int -> Int -> DataFrame` (same)

Also, I think there should exist a method for retrieving `Column` objects, not the dataframes. Otherwise there will be a lot of unpacking involved. For example, I guess the `selectColumn :: Int -> Column` method would be quite convenient (Pandas would return a `Series` in such case).

Question: can we easily define a `map` function for `Column`s? It's incredibly useful. Also, an `apply`-like method for mapping a function over each row would be awesome! ;)

**Comment by kustosz** [comment]
@piotrMocz good to have you here – please share your thoughts on how to properly handle NAs. Any ideas? I'm talking implementation–level, how do you store them efficiently. Any useful pandas experience on your part?

**Comment by sylwiabr** [comment]
Probably we will need more functionalities but It is usable and we can add more later Repository: https://github.com/luna-packages/Dataframes

**Comment by kustosz** [comment]
– The C extensions are drowning in debug prints and hardcoded paths to your home dir in the debug bits. Please cleanup.
– The `scanf` function is misleading – either make it into a real `scanf` or name that `parseDouble`.
– The `Main.luna` hardcodes local debug path.

To say more I need you to guide me through the code, too much happening at once :)

**Comment by kustosz** [comment]
@sylwiabr 

* My previous comment about `scanf` still stands
* The library lacks a Readme and a Makefile for foreign code.
* It lacks visualization facilities – the `Main` file seems to compile and outputs the file, but since I cannot see anything inside Luna Studio, I have no way of testing it further.
