### ISSUE TITLE
CSV implementations

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna#221]
Basic implementation for handling CSV files.

**Comment by kustosz** [comment]
@sylwiabr 

I have not tested it thoroughly because of the lack of visualizers inside Dataframes.
However, I can already say something is wrong – why does the generated CSV file quote everything? In particular numbers, which should not be the case. Numbers should be generated without quotes for other engines to handle them properly.

**Comment by sylwiabr** [comment]
@kustosz  CSV file can have quotes on each value and it is not a mistake, if the value has a space it has to be quoted (see: https://en.wikipedia.org/wiki/Comma-separated_values)
The example was suppoused to read csv file, delete a column and write for csv part.

**Comment by lgawlik** [comment]
- to test: read and write any CSV file

**Comment by sylwiabr** [comment]
I think since we are working on https://github.com/luna/Dataframes and testing it widely we can close this issue.
