### ISSUE TITLE
Build time performance of luna-core

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna#231]
The https://github.com/luna/luna-core repository is very slow to build (> 1h) and requires tons of RAM (> 16 GB). I have written down some observation. Please note that I don't really know this codebase and measurements are not very accurate. The purpose is rather to find parts of luna-core that need their maintainers' attention and to give them something to start investigation with.

My machine is i7-4900K with 16 GB RAM.

First I have observed which packages seem to need lots of time or memory to build. Then I build them one by one and observed which modules in them are particularly heavy.
* `luna-passes` is by far the worst offender, it seems to require 18 GB of memory and takes 37m48s to build.
    * Luna.Pass.Sourcing.ClassProcessor 
    * Luna.Pass.Typing.HeaderBuilder — 5m to build this single file; when building, memory exceeds 16 GB
    * many Desugar passes are slow to build, including:
    * Luna.Pass.Transform.Desugar.DesugarFieldModifiers
    * Luna.Pass.Transform.Desugar.DesugarPartialApplications
* `luna-syntax-text-parser` 7m15s 8,46 GB
    * Luna.Syntax.Text.Parser.IR.Term takes almost whole time
* `luna-core` the first module in the build order that crosses 8 GB of RAM. Build takes about 6m45s. Particularly two modules seem to be resource-heavy:
    * luna-core/core/src/Luna/IR/Term/Core.hs
    * Luna.IR.Term.Ast.Class
    Both of them use template haskell and `[d| … |]` quasiquotation.
* `luna-syntax-text-lexer` 2m45s, ~8 GB
    * Luna.Syntax.Text.Lexer.Grammar
* `luna-package` 3m, ~11GB
    * Luna.Package.Configuration.License — I really see no reason why this module is so slow to build and use ~11 GB but this is wrong.

Preferably memory usage for any single package should stay way below 8GB, please remember that several packages can be built side-by-side and having non-deterministic build failures because of exhausted memory is bad.

**Comment by wdanilo** [comment]
Awesome breakdown! Few notes from my side:

1. `luna-core` is like "CPP template library", while `luna-passes` generates and optimizes the final code from the templates (solving a ton of type families). Further investigation needed here, but see my notes below.

2. `luna-syntax-text-parser` I'm afraid we cannot do much here, but let's break it down further:
  - Monadic parser complexity. Using monadic parsers allow us to use _very_ high level API so making it running fast requires a ton of optimizations. However, I feel GHC consumes more than it should here. 
  - Our parser combinator usage is very specific, because we are again building some kind of "CPP template" out of it, because we do not know while compiling the file, what set of layers our nodes would have. We are using right now `SmallVector` and `SmallSet` implementations everywhere where we used to have dynamic containers. It allows us to create some magic here and monomorphise the whole parser. I don't know if it would help much, but it's worth checking out (it would take ~ 1 whole day of my time + 2 days to adjust rest of the API if it will work).

3. `luna-core` - the problem with these two files is not TemplateHaskell per se, rather the code it generates. The code uses a ton of type families to compute types in smart constructors. See notes below.

4. `luna-syntax-text-lexer` - this is a surprise for me. Worth checking out.

5. `luna-package` - WTF. @iamrecursion have you seen it?


**Side notes**  
The points 1 and 3 above refer to a very specific use case, where we've got a LOT of type families to be resolved. There was a famous fix in GHC Head if I'm not wrong (any link would be appreciated - I cannot find it now) regarding drastic speedup of type family resolution. Basically I'm pretty sure it will affect our compilation times and memory usage in a very positive way and we need to check it out.

**Comment by mwu-tow** [comment]
As for the fix on the GHC side — does anything listed on the [status page for GHC 8.6 ](https://ghc.haskell.org/trac/ghc/wiki/Status/GHC-8.6.1) looks relevant? 
[GHC 8.6.1 alpha2](https://downloads.haskell.org/~ghc/8.6.1-alpha2/) has been recently released, if we knew that fix has landed there, we should test it.

**Comment by wdanilo** [comment]
Ok, I've got it, here it is: https://phabricator.haskell.org/D4766

**Comment by mwu-tow** [comment]
The change indeed looks very promising but apparently it is still under review, so it is unknown when it will be merged. Given that GHC 8.6 has been already branched, I'm afraid that the fix will target 8.8 at best. 

Perhaps it would be possible to patch 8.4.2 (which we use) to test it, but relying on custom build of GHC is a particular kind of hell that I really don't want come back to.

**Comment by iamrecursion** [comment]
The offender in `Luna.Package.Configuration.License` is potentially the quasiquoters. I'll refactor the file.

**Comment by iamrecursion** [comment]
Hopefully refactoring the above to use cabal's `data-files` ability reduces compile memory usage. Take a look. It is now in HEAD of core, merged from [luna-core/pull/132](https://github.com/luna/luna-core/pull/132).

**Comment by mwu-tow** [comment]
Unfortunately I see not improvement in `Luna.Package.Configuration.License` as of luna/luna-core@1370eef1164a6d2e04e025bffef2997896b31e3a — package still takes over 3m to build using up to 11.7 GB.

I have tried replacing parser code in https://github.com/luna/luna-core/blob/1370eef1164a6d2e04e025bffef2997896b31e3a/package/src/Luna/Package/Configuration/License.hs#L94
with `license = pure MIT` and that improved things: build time went down to 54s and memory usage to 1,6 GB.

@wdanilo  Any idea why the linked parser code needs 2 minutes and 10GB to build? It looks like it should be a relatively simple parser, such resource usage is surprising.
