### ISSUE TITLE
-1.0 not parsing properly

### ISSUE THREAD

**Issue by mikusp** [luna/luna#308]
Please ensure that you are running the latest version of Luna before reporting the bug! It may have been fixed since.

### General Summary

Expressions like `-1.0` are not parsed correctly.

### Steps to Reproduce

1. Add node `-1.0` or `(-1.0)`

### Expected Result

Node with expression printed as `-1.0`

### Actual Result

![zrzut ekranu z 2018-10-10 12-29-25](https://user-images.githubusercontent.com/2052578/46730383-46307700-cc88-11e8-858e-f363a2e490ee.png)

### Luna Version
Commit 6f1a6ebaaa4ffc6ec5b07fe19c170001f6e313eb

**Comment by jcmincke** [comment]
I think it is even worse:

`1+2` compiles fine
`1 + 2` compiles fine
`1 +2` fails, the compiler consider 1 as a function

We have the same behaviour with other types (float, strings etc):
`"s" +"k"` fails

**Comment by wdanilo** [comment]
@jcmincke The original report was about treating `-1` as a lambda `x: x-1`, which clearly was wrong and it was fixed in a new parser (I think it's not public yet). However, your examples behave correctly. Luna spaces affect the operator precedences, it's described in the docs, so for example, `1 +2` is just the same as `1 +2`. It allows for writing very expressive things like `[1 .. 10] . each random . sort . take 10` or `lst' = lst.map +1`.
