### ISSUE TITLE
Allowing comments to be hidden in docs.

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna#56]
```
# not a docstring at all, just a comment for the devs using this private function
def _foo a b:
    a + b
```
I would expect code like this to work just fine: it's a comment, not a docstring (I don't want it to be one).

**Comment by ricardopieper** [comment]
I tried adding 2 tests on ParserSpec.hs:

            it "disabled block over function"            $ shouldParseItself' expr   "#comment\n«2»def test: 1### META {\"metas\":[]}" [(0,0)]   
            it "disabled block over function, no metadata" $ shouldParseItself' expr "#comment\ndef test: 1" [(0,0)]

I have no idea what I should put on [(0,0)] but that's a problem for another time. 
The problem is that I couldn't reproduce the problem in the unit tests: Those tests fail with `unexpected Token 1 0 EOL :| []`, while in Luna Studio (1.0) I get a `unexpected Token 1 0 Disable :| [] expecting marker CallStack`

I haven't located the bug on Parsing.hs and don't even know where it could be. However, one thing that I noticed is that the parsing exception is a bit weird:

![image](https://user-images.githubusercontent.com/4030858/35196168-894d1148-feb5-11e7-82d8-30f9dd1b7b8c.png)

Looking at `Parser error: 1:63 unexpected Token 1 0 Disable`, it seems like the Compiler is considering everything to be in a single line. Is 1:63 supposed to be $line:$col or is it another thing?

**Comment by wdanilo** [comment]
Oh, there is some bigger misunderstanding here from the beginning (including the original post by @piotrMocz). I don't know why I haven't seen it before!

In current Luna design this is not a bug. We've got 2 comment syntaxes here:

1. Disable comments (starting with `#`), which basically disable following block of code and display corresponding nodes grayed out. these comments work for code blocks, not lines, for example:
```haskell
# def foo a b:
    c = a + b
    print c
```
will "comment out" the whole function `foo`, not only the first line.

2. Doc comments (starting with `##`), which behave like regular comments in other languages. 

The original issue by @piotrMocz was that he wanted to use doc comments but hide them in documentation. This is a feature / new design request, not a bug fixing request. We do not yet know what would be the best way to support it, but I'm open for any discussion here!

**Comment by wdanilo** [comment]
Ok, some time passed, we've got new parser here and I want to resurrect this topic. I don't see a point to allow comments just before function definition that are not considered to describe this function and thus be doc comments. If you want this function to be skipped in the docs, just use underscore on the beginning of its name and make it private / hidden. Or just refactor it to other module. I would like to see Luna simple in every design decision. When you write comment before a variable / definition then it's just the description (read - the doc) of it.

**Comment by piotrMocz** [comment]
Since I was the one to open this issue, I feel like I can be the one to close it. I agree with @wdanilo :)
