### ISSUE TITLE
Missing installer support for HTTP proxied internet connection (Win7)

### ISSUE THREAD

**Issue by asemt** [luna/luna#81]
Hi there,

unfortunately I could not try the Luna language due to the fact that I'm behind a HTTP proxy and the installer is not picking up the Windows 7 proxy configuration automatically (and does not provide a way to define the proxy settings manually, it seems). Following error occurs:

```
Couldn't download file: http://packages.luna-lang.org/config.yaml because of: HttpExceptionRequest Request {
  host                 = "packages.luna-lang.org"
  port                 = 80
  secure               = False
  requestHeaders       = []
  path                 = "/config.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure connect: failed (Connection timed out (WSAETIMEDOUT)))
```

Affected version: 1.0 beta

*Thanks for such a wonderful language!*

**Comment by sneusse** [comment]
Ok, some info:

When I start the installer and copy the extracted contents to another directory, set the environment variables http_proxy and https_proxy it works - kind of.

Now the process fails with this error:
Prelude.head: empty list

**Comment by wdanilo** [comment]
> Thanks for such a wonderful language!
Thank you so much!!!

Our Windows team is under heavy work right now, we will try to investigate it asap. Please try the 1.0.1 version, the PHEL problem should be fixed by now!

**Comment by TimoSta** [comment]
Unfortunately, I'm facing the same issue with the most recent version provided on the website run on Win 7. Sitting behind a corporate proxy.

Happy to provide additional info if required.

```
Couldn't download file: http://packages.luna-lang.org/config.yaml because of: HttpExceptionRequest Request {
  host                 = "packages.luna-lang.org"
  port                 = 80
  secure               = False
  requestHeaders       = []
  path                 = "/config.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure connect: failed (Connection timed out (WSAETIMEDOUT)))

```
![image](https://user-images.githubusercontent.com/5621996/35642210-662ae3ce-0690-11e8-9556-6abecb263139.png)

**Comment by 1600** [comment]
https://github.com/luna/luna/labels/S%20-%20Help%20Wanted

**Comment by acaramia** [comment]
Hi, same problem here with luna 1.2 beta.

Couldn't download file: http://packages.luna-lang.org/config.yaml because of: HttpExceptionRequest Request {
  host                 = "packages.luna-lang.org"
  port                 = 80
  secure               = False
  requestHeaders       = []
  path                 = "/config.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure connect: failed (Connection timed out (WSAETIMEDOUT)))

Is it possible to use the luna-manager in w7 to bypass this issue?
Thanks

**Comment by jeffyboz** [comment]
I'm getting the same error - would you possibly have an image I could demo?

**Comment by kustosz** [comment]
@acaramia @jeffyboz Are you able to download the config.yaml file manually (from browser)? If yes, here's something that should help: we have recently added an option for local installs to the Luna Manager.
Download that file and get a luna-manager for your platform here: https://github.com/luna/luna-manager/releases/tag/1.1.4
After that, run the luna manager like this:
```
luna-manager install --nightly --config PATH_TO_CONFIG_YAML --verbose
```
Note that on Windows you need to run this from Admin Powershell. On macOS and linux any shell will do.
This will resolve versions from the local file instead of the remote config. The package itself is downloaded over https from github, so that should be much of a problem. If it doesn't help, let me know, we'll figure something more "manual" out :)

**Comment by acaramia** [comment]
Hi, 
>

> Are you able to download the config.yaml file manually (from browser)?

YES so, I'll try what you suggest. 

In the meantime I have already downloaded lua-manager and I'm using Cygwin (http://babun.github.io/)  
from Cygwin: 
```
./luna-manager install   
Couldn't download file: http://packages.luna-lang.org/config.yaml because of: HttpExceptionContentWrapper 
{unHttpExceptionContentWrapper = InvalidProxyEnvironmentVariable "https_proxy" "https://xxxxxxx"}
```

so i changed the **https_proxy** env variable to **http (instead of https)**
`export https_proxy=http://myproxy.xxx.yyy:9999`

and lua-manager is now running:
`Downloading repository configuration file (http://packages.luna-lang.org/config.yaml)`

**Comment by acaramia** [comment]
@kustosz 
I tried 
`luna-manager install --nightly --config PATH_TO_CONFIG_YAML --verbose`
with Administrator PowerShell
after few questions, 
```
Downloading: https://github.com/luna/luna-studio/releases/download/1.2.1/luna-studio-windows-1.2.1.tar.gz

Couldn't download file: https://github.com/luna/luna-studio/releases/download/1.2.1/luna-studio-windows-1.2.1.tar.gz bec
ause of: HttpExceptionRequest Request {
  host                 = "github.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/luna/luna-studio/releases/download/1.2.1/luna-studio-windows-1.2.1.tar.gz"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HostCannotConnect "github.com" [connect: failed (Connection timed out (WSAETIMEDOUT)),connect: failed (Connection timed out (WSAETIMEDOUT))]))
Manager version: 1.1.4
```

**Comment by jeffyboz** [comment]
Hi Guys,

I'm go-to-go now.  I took my computer to the IT Desk thinking there was a proxy issue - but the IT first tried to connect to the Windows store - he failed.  Then he ran an update that searched for issues.  It found a few then we rebooted.  It failed to connect to the Windows store again.  We ran the update search again - it found problems again.  After those had been fixed, we connected to the Windows successfully without rebooting.  Then I could connect to 443 on github and everything is installed.  I haven't tried anything yet, but thanks for being so responsive!!

Cheers,
Jeff

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kustosz** [comment]
@acaramia so there's some more manual labor, but this should not run into any more problems with networking. Download the `luna-studio-windows-1.2.1.tar.gz` file from where the manager tries to get it. Then use this:
```
apps:
- luna-studio
packages:
  luna-studio:
    versions:
      1.2.1:
        windows.x64:
          path: <ABSOLUTE PATH TO luna-studio-windows-1.2.1.tar.gz>
          deps: []
    synopsis: studio synopsis
    appType: GuiApp
```
as a template for the `config.yaml` file, fill it with the correct path to downloaded package and pass to `luna-manager` same as before. This time it won't try to download anything, just use the local file.

**Comment by sylwiabr** [comment]
one additional information: you need to download luna-studio-windows-1.2.1.sha256 file and put it next to package -> it will try to check the checksum

**Comment by sylwiabr** [comment]
Issue moved to [luna/luna-manager #244](https://github.com/luna/luna-manager/issues/244) via [**ZenHub**](https://www.zenhub.com/)
