### ISSUE TITLE
"Go to Declaration" does not work

### ISSUE THREAD

**Issue by thSoft** [luna/luna#84]
Luna: 1.0 beta
macOS: 10.12.6

In the textual editor, when I right click a reference and select `Go to declaration`, the declaration should be revealed but nothing happens.

**Comment by wdanilo** [comment]
We do not support "go to declaration" now. I mark this as feature request, but my rough estimate is that it will not be available very soon, because we've got several very high priority tasks right now. If you, or anybody else, want to help us with this, we'd love to guide you in the right direction how to dig into the compiler and query it for name resolution.

**Comment by Gurkenglas** [comment]
Imo hiding the `Go to declaration` button for the time being should have bug-level priority.

**Comment by wdanilo** [comment]
@Gurkenglas Right. I know however, we couldn't touch it anytime soon. Would you like to help us with it guys? :)

**Comment by iamrecursion** [comment]
Downgrading priority of this as a compiler issue and re-labelling in preference to the UX issue mentioned here: https://github.com/luna/luna-studio/issues/800

**Comment by wdanilo** [comment]
Downgrading it even more as we are planning to go atomless and this issue does not hurt anybody much.
